version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - './front-end:/app'
      - '/front-end/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
